Task/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.task_list, name='task-list'),
    path('create/', views.create_task, name='task-create'),
    path('<int:pk>/update/', views.task_update, name='task-update'),
    path('<int:pk>/delete/', views.task_delete, name='task-delete'),
]

Task_Management_System/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home,  name="home"),
    path('', views.home,  name="home"),
    path('/#contact/', views.submit_feedback, name="contact"),
    path('faqs/', views.faq, name="faq"),
    path('user/', include('Users.urls')),
    path('task/', include('Task.urls')),
]    

Task/models.py
# Create your models here.

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Task(models.Model):
    CATEGORY_CHOICES = [
        ('work', 'Work'),
        ('personal', 'Personal'),
        ('other', 'Others'),
    ]

    PRIORITY_CHOICES = [
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
    ]

    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
    ]

    title = models.CharField(max_length=100)
    description = models.TextField()
    category = models.CharField(max_length=10, choices=CATEGORY_CHOICES, default="Choose any")
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default="Choose any")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pending')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deadline = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

Task/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'category', 'priority', 'status', 'deadline']
        widgets = {
            'deadline': forms.DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M:%S'),
        }
        labels = {
            'title' : 'Task Title',
            'description' : 'Task Description',
            'category' : 'Category',
            'priority' : 'Priority',
            'status' : 'Status',
            'deadline' : 'Deadline',
        }

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        
        # self.fields['category'].widget = forms.Select()
        # self.fields['priority'].widget = forms.Select()
        # self.fields['status'].widget = forms.Select()

        self.fields['deadline'].input_formats = ['%Y-%m-%dT%H:%M:%S']

    

Task/views.py
# Create your views here.

from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from .models import Task
from .forms import TaskForm
# from django.contrib.auth.decorators import login_required

# @login_required

def task_list(request):
    tasks = Task.objects.filter(user=request.user)

    priority_filter = request.GET.get('priority')
    category_filter = request.GET.get('category')
    status_filter = request.GET.get('status')

    if priority_filter:
        tasks = tasks.filter(priority=priority_filter)
    if category_filter:
        tasks = tasks.filter(category=category_filter)
    if status_filter:
        tasks = tasks.filter(status=status_filter)

        
    return render(request, 'tasks/task_list.html', {'tasks' : tasks})

def create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            print(messages.success(request, 'Task was successfully created.'))
            return redirect('task-list')
    else:
        form = TaskForm()
        print(messages.error)
    return render(request, 'tasks/task_form.html', {'form': form})

def task_update(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            print(messages.success(request, 'Task was successfully updated.'))
            return redirect('task-list')
    else:
        form = TaskForm(instance=task)
        print(messages.error)

    return render(request, 'tasks/task_update_form.html', {'form' : form})

def task_delete(request, pk):
    tasks = get_object_or_404(Task, pk=pk)
    
    if request.method == 'POST':
        tasks.delete()
        print(messages.success(request, 'Task was successfully deleted.'))
        return redirect('task-list')
    
    return render(request, 'tasks/task_confirm_delete.html', {'task': tasks})

templates/tasks/task_confirm_delete.html
{% extends 'layouts.html' %}
{% load static %}


{% block title %}

    Delete Tasks
    
{% endblock title %}


{% block stylepage %}

    <link rel="stylesheet" href="{% static '/css/taskDelete.css' %}">

{% endblock stylepage %}


{% block content %}

    <div class="homepage2">
        <div class="homepage">
            <div class="container">
                <h1>Delete Task</h1>
                <p>Are you sure you want to delete the task "<strong>{{ task.title }}</strong>"?</p>
                <p><strong>Description:</strong> {{ task.description }}</p>
                <p><strong>Priority:</strong> {{ task.get_priority_display }}</p>
                <p><strong>Category:</strong> {{ task.get_category_display }}</p>
                <p><strong>Status:</strong> {{ task.get_status_display }}</p>
                <p><strong>Deadline:</strong> {{ task.deadline|date:"F d, Y H:i" }}</p>
            
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn-delete">Confirm Delete</button>
                    <a href="{% url 'task-list' %}" class="btn-cancel">Cancel</a>
                </form>
            </div>
        </div>
    </div>
    
{% endblock content %}

templates/tasks/task_form.html
{% extends 'layouts.html' %}
{% load static %}


{% block title %}

    Create Tasks
    
{% endblock title %}


{% block stylepage %}

    <link rel="stylesheet" href="{% static '/css/taskForm.css' %}">

{% endblock stylepage %}


{% block content %}

    <div class="homepage2">
        <div class="homepage">
            <div class="container">
                <h1>Create a New Task</h1>
                
                <!-- Form -->
                <form method="POST">
                    {% csrf_token %}
                                        
                    <div class="form-control">
                        {{ form.title.label_tag }}
                        {{ form.title }}
                        {% if form.title.errors %}
                            <div class="errorlist">{{ form.title.errors }}</div>
                        {% endif %}
                    </div>
        
                    <div class="form-control">
                        {{ form.description.label_tag }}
                        {{ form.description }}
                        {% if form.description.errors %}
                            <div class="errorlist">{{ form.description.errors }}</div>
                        {% endif %}
                    </div>
        
                    <div class="form-control">
                        {{ form.category.label_tag }}
                        {{ form.category }}
                        {% if form.category.errors %}
                            <div class="errorlist">{{ form.category.errors }}</div>
                        {% endif %}
                    </div>
                    
                    <div class="form-control">
                        {{ form.priority.label_tag }}
                        {{ form.priority }}
                        {% if form.priority.errors %}
                            <div class="errorlist">{{ form.priority.errors }}</div>
                        {% endif %}
                    </div>
                    
                    <div class="form-control">
                        {{ form.status.label_tag }}
                        {{ form.status }}
                        {% if form.status.errors %}
                            <div class="errorlist">{{ form.status.errors }}</div>
                        {% endif %}
                    </div>                
        
                    <div class="form-control">
                        {{ form.deadline.label_tag }}
                        {{ form.deadline }}
                        {% if form.deadline.errors %}
                            <div class="errorlist">{{ form.deadline.errors }}</div>
                        {% endif %}
                    </div>
    
                    
                    <!-- Submit button -->
                    <button type="submit" class="btn-submit">Create Task</button>
                </form>
        
                <!-- Back to task list link -->
                <a href="{% url 'task-list' %}" class="btn-back">Back to Task List</a>
            </div>
        </div>
    </div>
    
{% endblock content %}


    

templates/tasks/task_list.html
{% extends 'layouts.html' %}
{% load static %}


{% block title %}

    My Tasks
    
{% endblock title %}


{% block stylepage %}

    <link rel="stylesheet" href="{% static '/css/taskList.css' %}">

{% endblock stylepage %}


{% block content %}

    <div class="homepage2">
        <div class="homepage">
            <div class="container">
                <h1>My Task List</h1>
        
                <!-- Filter by Priority -->
                <div>
                    <form class="task-filter" method="GET">
                        <select name="priority">
                            <option value="">Priority</option>
                            <option value="low" {% if request.GET.priority == "low" %}selected{% endif %}>Low</option>
                            <option value="medium" {% if request.GET.priority == "medium" %}selected{% endif %}>Medium</option>
                            <option value="high" {% if request.GET.priority == "high" %}selected{% endif %}>High</option>
                        </select>
                        <select name="category">
                            <option value="">Category</option>
                            <option value="work" {% if request.GET.priority == "work" %}selected{% endif %}>Work</option>
                            <option value="personal" {% if request.GET.priority == "personal" %}selected{% endif %}>Personal</option>
                            <option value="other" {% if request.GET.priority == "other" %}selected{% endif %}>Others</option>
                        </select>
                        <select name="status">
                            <option value="">Status</option>
                            <option value="pending" {% if request.GET.priority == "pending" %}selected{% endif %}>Pending</option>
                            <option value="in_progress" {% if request.GET.priority == "in_progress" %}selected{% endif %}>In Progress</option>
                            <option value="completed" {% if request.GET.priority == "completed" %}selected{% endif %}>Completed</option>
                        </select>
                        <button type="submit">Filter</button>
                        <a href="{% url 'task-list' %}" class="btn-clear">Clear Filter</a>
                    </form>
                    
                </div>
                
                <a href="{% url 'task-create' %}" class="create-task-btn">Create New Task</a>

                
    
                <!-- Task List -->
                <ul class="task_list">
                    {% if tasks %}
                        {% for task in tasks %}
                            <li class="task-item priority-{{ task.priority }}">
                                <h3>{{ task.title }}</h3>
                                <p>{{ task.description }}</p>
                                <div class="task-meta">
                                    <span>Category: {{ task.get_category_display }}</span> |
                                    <span>Priority: {{ task.get_priority_display }}</span> |
                                    <span>Status: {{ task.get_status_display }}</span> |
                                    <span>Deadline: {{ task.deadline|date:"F d, Y H:i" }}</span>
                                </div>
    
                                <!-- Update and Delete Buttons -->
                                <div class="task-actions">
                                    <a href="{% url 'task-update' task.id %}" class="btn-update">Update</a>
                                    <a href="{% url 'task-delete' task.id %}" class="btn-delete">Delete</a>
                                </div> 
    
                            </li>
                        {% endfor %}
                    {% else %}
                        <p>No tasks found.</p>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    
{% endblock content %}


    





    

templates/tasks/task_update_form.html
{% extends 'layouts.html' %}
{% load static %}


{% block title %}

    Update Tasks
    
{% endblock title %}


{% block stylepage %}

    <link rel="stylesheet" href="{% static '/css/taskForm.css' %}">

{% endblock stylepage %}


{% block content %}

    <div class="homepage2">
        <div class="homepage">
            <div class="container">
                <h1>Update Task</h1>
                
                <!-- Form -->
                <form method="POST">
                    {% csrf_token %}
                    
                    
                    <div class="form-control">
                        {{ form.title.label_tag }}
                        {{ form.title }}
                        {% if form.title.errors %}
                            <div class="errorlist">{{ form.title.errors }}</div>
                        {% endif %}
                    </div>
        
                    <div class="form-control">
                        {{ form.description.label_tag }}
                        {{ form.description }}
                        {% if form.description.errors %}
                            <div class="errorlist">{{ form.description.errors }}</div>
                        {% endif %}
                    </div>
        
                    <div class="form-control">
                        {{ form.category.label_tag }}
                        {{ form.category }}
                        {% if form.category.errors %}
                            <div class="errorlist">{{ form.category.errors }}</div>
                        {% endif %}
                    </div>
                    
                    <div class="form-control">
                        {{ form.priority.label_tag }}
                        {{ form.priority }}
                        {% if form.priority.errors %}
                            <div class="errorlist">{{ form.priority.errors }}</div>
                        {% endif %}
                    </div>
                    
                    <div class="form-control">
                        {{ form.status.label_tag }}
                        {{ form.status }}
                        {% if form.status.errors %}
                            <div class="errorlist">{{ form.status.errors }}</div>
                        {% endif %}
                    </div>                
        
                    <div class="form-control">
                        {{ form.deadline.label_tag }}
                        {{ form.deadline }}
                        {% if form.deadline.errors %}
                            <div class="errorlist">{{ form.deadline.errors }}</div>
                        {% endif %}
                    </div>
    
                    
                    <!-- Submit button -->
                    <button type="submit" class="btn-submit">Edit Task</button>
                </form>
        
                <!-- Back to task list link -->
                <a href="{% url 'task-list' %}" class="btn-back">Back to Task List</a>
            </div>
        </div>
    </div>
    
{% endblock content %}


    